---
title: "week 5"
author: "wafo"
date: "2026-02-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggthemes)
library(viridis)
library(hexbin)
```

```{r}
HDBPropertyInformation <- read_csv("../data/HDBPropertyInformation.csv")
```
```{r fig.height=2, fig.width=6}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl)) + 
  geom_boxplot()
```
```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=bldg_contract_town)) + 
  geom_boxplot()
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units)) + 
  geom_point(alpha=0.1)
```
```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units)) + 
  geom_count()
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units)) + 
  geom_bin2d()
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units)) + 
  geom_hex()
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units, colour = year_completed)) + 
  geom_jitter(size = 0.2)
```
```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units, color = year_completed)) + 
  geom_jitter(size = 0.2) + 
  facet_wrap(~ commercial)
```
```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units, color = year_completed)) + 
  geom_jitter(size = 0.2) + 
  facet_wrap(~ bldg_contract_town)
```
```{r fig.height=10, fig.width=40}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units, color = year_completed)) + 
  geom_jitter(size = 0.2) + 
  facet_grid(~ commercial ~ bldg_contract_town)
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=max_floor_lvl, y=total_dwelling_units, color = year_completed)) + 
  geom_jitter(size = 0.2) + 
  facet_grid(~ commercial ~ residential)
```

```{r}
ggplot(data = HDBPropertyInformation, mapping = aes(x=year_completed, y=max_floor_lvl, color = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  geom_smooth()
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, color = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  geom_smooth()
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, color = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  xlim(1960, 2025) +
  geom_smooth()
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, color = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  xlim(1960, 2025) +
  geom_smooth() +
  labs(title = 'Relation between year completed and max floor number', subtitle = 'Analysis of HDB building', caption = 'Data source: HDB (2026).', x = 'Year of completion (1960-2025)', y = 'Number of floors', colour = 'year') +
  theme_classic()
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, color = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  xlim(1960, 2025) +
  geom_smooth() +
  labs(title = 'Relation between year completed and max floor number', subtitle = 'Analysis of HDB building', caption = 'Data source: HDB (2026).', x = 'Year of completion (1960-2025)', y = 'Number of floors', colour = 'year') +
  theme_classic()

ggsave('hdbscattor.png')
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, colour = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  xlim(1960, 2025) +
  geom_smooth() +
  labs(title = 'Relation between year completed and max floor number', subtitle = 'Analysis of HDB building', caption = 'Data source: HDB (2026).', x = 'Year of completion (1960-2025)', y = 'Number of floors', colour = 'year') +
  theme_minimal() + 
  scale_colour_distiller(palette = 'Oranges', direction=1)
```
```{r}
ggplot(data = subset(HDBPropertyInformation, residential == 'Y'), mapping = aes(x=year_completed, y=max_floor_lvl, colour = year_completed)) + 
  geom_jitter(alpha = 0.2) + 
  xlim(1960, 2025) +
  geom_smooth() +
  labs(title = 'Relation between year completed and max floor number', subtitle = 'Analysis of HDB building', caption = 'Data source: HDB (2026).', x = 'Year of completion (1960-2025)', y = 'Number of floors', colour = 'year') +
  theme_minimal() + 
  scale_colour_viridis()
```

